//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap applications_16 {
            get {
                object obj = ResourceManager.GetObject("applications_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all watch entries ?.
        /// </summary>
        internal static string Breakpoints_Delete_Confirmation {
            get {
                return ResourceManager.GetString("Breakpoints_Delete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakpoints: Off.
        /// </summary>
        internal static string Breakpoints_Off {
            get {
                return ResourceManager.GetString("Breakpoints_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakpoints: On.
        /// </summary>
        internal static string Breakpoints_On {
            get {
                return ResourceManager.GetString("Breakpoints_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Viewer Breakpoints|*.pvwm|All Files|*.*.
        /// </summary>
        internal static string BreakpointsFile {
            get {
                return ResourceManager.GetString("BreakpointsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okey.
        /// </summary>
        internal static string Button_Okey {
            get {
                return ResourceManager.GetString("Button_Okey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Value.
        /// </summary>
        internal static string Button_ResetValue {
            get {
                return ResourceManager.GetString("Button_ResetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_16 {
            get {
                object obj = ResourceManager.GetObject("calendar_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_16 {
            get {
                object obj = ResourceManager.GetObject("cancel_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_161 {
            get {
                object obj = ResourceManager.GetObject("cancel_161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Cat_Appearance {
            get {
                return ResourceManager.GetString("Cat_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        internal static string Cat_Behaviour {
            get {
                return ResourceManager.GetString("Cat_Behaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Cat_Data {
            get {
                return ResourceManager.GetString("Cat_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string Cat_Detail {
            get {
                return ResourceManager.GetString("Cat_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string Cat_Layout {
            get {
                return ResourceManager.GetString("Cat_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string Cat_Operation {
            get {
                return ResourceManager.GetString("Cat_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Cat_Parameter {
            get {
                return ResourceManager.GetString("Cat_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Window.
        /// </summary>
        internal static string Cmd_DisableWindow {
            get {
                return ResourceManager.GetString("Cmd_DisableWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Window.
        /// </summary>
        internal static string Cmd_EnableWindow {
            get {
                return ResourceManager.GetString("Cmd_EnableWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Window.
        /// </summary>
        internal static string Cmd_HideWindow {
            get {
                return ResourceManager.GetString("Cmd_HideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        internal static string Cmd_Highlight {
            get {
                return ResourceManager.GetString("Cmd_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidate.
        /// </summary>
        internal static string Cmd_Invalidate {
            get {
                return ResourceManager.GetString("Cmd_Invalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        internal static string Cmd_KillProcess {
            get {
                return ResourceManager.GetString("Cmd_KillProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen Messages.
        /// </summary>
        internal static string Cmd_ListenMessages {
            get {
                return ResourceManager.GetString("Cmd_ListenMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Cmd_RefreshProcess {
            get {
                return ResourceManager.GetString("Cmd_RefreshProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Key.
        /// </summary>
        internal static string Cmd_SendKey {
            get {
                return ResourceManager.GetString("Cmd_SendKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Window.
        /// </summary>
        internal static string Cmd_ShowWindow {
            get {
                return ResourceManager.GetString("Cmd_ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Listening.
        /// </summary>
        internal static string Cmd_StopListening {
            get {
                return ResourceManager.GetString("Cmd_StopListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap confirm_16 {
            get {
                object obj = ResourceManager.GetObject("confirm_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_16 {
            get {
                object obj = ResourceManager.GetObject("copy_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets o sets that is this message will be ignored or not ?.
        /// </summary>
        internal static string Des_EditMessage_Ignore {
            get {
                return ResourceManager.GetString("Des_EditMessage_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the LParam of the message.
        /// </summary>
        internal static string Des_EditMessage_LParam {
            get {
                return ResourceManager.GetString("Des_EditMessage_LParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to change the incoming message to a different message set this property..
        /// </summary>
        internal static string Des_EditMessage_ModifiedMsg {
            get {
                return ResourceManager.GetString("Des_EditMessage_ModifiedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the message which we are editing now.
        /// </summary>
        internal static string Des_EditMessage_Msg {
            get {
                return ResourceManager.GetString("Des_EditMessage_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the WParam of the message.
        /// </summary>
        internal static string Des_EditMessage_WParam {
            get {
                return ResourceManager.GetString("Des_EditMessage_WParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the action that PV will apply as soon as system sends this message to the hooked window..
        /// </summary>
        internal static string Des_MessageBreakpoint_Action {
            get {
                return ResourceManager.GetString("Des_MessageBreakpoint_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the lParam value, which will be replaced with the original Param when the Action is AutoChangeParams.
        /// </summary>
        internal static string Des_MessageBreakpoint_LParam {
            get {
                return ResourceManager.GetString("Des_MessageBreakpoint_LParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the sections which Process Viewer will modify automatically.
        /// </summary>
        internal static string Des_MessageBreakpoint_Modifications {
            get {
                return ResourceManager.GetString("Des_MessageBreakpoint_Modifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If not WM_NULL then Process Viewer will replace the incoming message with this message..
        /// </summary>
        internal static string Des_MessageBreakpoint_ModifiedMsg {
            get {
                return ResourceManager.GetString("Des_MessageBreakpoint_ModifiedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the Windows message.
        /// </summary>
        internal static string Des_MessageBreakpoint_Msg {
            get {
                return ResourceManager.GetString("Des_MessageBreakpoint_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the wParam value, which will be replaced with the original wParam when the Action is AutoChangeParams.
        /// </summary>
        internal static string Des_MessageBreakpoint_WParam {
            get {
                return ResourceManager.GetString("Des_MessageBreakpoint_WParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the Hi-Order Word of this parameter.
        /// </summary>
        internal static string Des_MessageParam_HiWord {
            get {
                return ResourceManager.GetString("Des_MessageParam_HiWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the Low-Order Word of this parameter.
        /// </summary>
        internal static string Des_MessageParam_LoWord {
            get {
                return ResourceManager.GetString("Des_MessageParam_LoWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the value of this parameter.
        /// </summary>
        internal static string Des_MessageParam_Value {
            get {
                return ResourceManager.GetString("Des_MessageParam_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the bounds of this window.
        /// </summary>
        internal static string Des_WindowInfo_Bounds {
            get {
                return ResourceManager.GetString("Des_WindowInfo_Bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets that is this control has capturing.
        /// </summary>
        internal static string Des_WindowInfo_Capture {
            get {
                return ResourceManager.GetString("Des_WindowInfo_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the ClassName of this window.
        /// </summary>
        internal static string Des_WindowInfo_ClassName {
            get {
                return ResourceManager.GetString("Des_WindowInfo_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets that is this window is enabled or not ?.
        /// </summary>
        internal static string Des_WindowInfo_Enabled {
            get {
                return ResourceManager.GetString("Des_WindowInfo_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the extended window styles of this window.
        /// </summary>
        internal static string Des_WindowInfo_ExStyles {
            get {
                return ResourceManager.GetString("Des_WindowInfo_ExStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the Handle of this window.
        /// </summary>
        internal static string Des_WindowInfo_Handle {
            get {
                return ResourceManager.GetString("Des_WindowInfo_Handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the location of this window.
        /// </summary>
        internal static string Des_WindowInfo_Location {
            get {
                return ResourceManager.GetString("Des_WindowInfo_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Parent window handle.
        /// </summary>
        internal static string Des_WindowInfo_ParentHandle {
            get {
                return ResourceManager.GetString("Des_WindowInfo_ParentHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the process id which owns this control.
        /// </summary>
        internal static string Des_WindowInfo_ProcessId {
            get {
                return ResourceManager.GetString("Des_WindowInfo_ProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the size of this window.
        /// </summary>
        internal static string Des_WindowInfo_Size {
            get {
                return ResourceManager.GetString("Des_WindowInfo_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the window styles of this window.
        /// </summary>
        internal static string Des_WindowInfo_Styles {
            get {
                return ResourceManager.GetString("Des_WindowInfo_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the Text of this window.
        /// </summary>
        internal static string Des_WindowInfo_Text {
            get {
                return ResourceManager.GetString("Des_WindowInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the thread id which owns this control.
        /// </summary>
        internal static string Des_WindowInfo_ThreadId {
            get {
                return ResourceManager.GetString("Des_WindowInfo_ThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets that is this window is visible or not ?.
        /// </summary>
        internal static string Des_WindowInfo_Visible {
            get {
                return ResourceManager.GetString("Des_WindowInfo_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap documents_16 {
            get {
                object obj = ResourceManager.GetObject("documents_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {Unknown process}.
        /// </summary>
        internal static string Err_UnknownProcess {
            get {
                return ResourceManager.GetString("Err_UnknownProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {Unknown window}.
        /// </summary>
        internal static string Err_UnknownWindow {
            get {
                return ResourceManager.GetString("Err_UnknownWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not enum or does not have Flags attribute. This editor supports only Enum values which has Flags attribute..
        /// </summary>
        internal static string Err_ValueIsNotEnumOrDoesNotHaveFlagsAttribute {
            get {
                return ResourceManager.GetString("Err_ValueIsNotEnumOrDoesNotHaveFlagsAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favorites_add_16 {
            get {
                object obj = ResourceManager.GetObject("favorites_add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Filter Messages &gt;.
        /// </summary>
        internal static string Filter_Key {
            get {
                return ResourceManager.GetString("Filter_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FndWnd {
            get {
                object obj = ResourceManager.GetObject("FndWnd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap go_16 {
            get {
                object obj = ResourceManager.GetObject("go_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_16 {
            get {
                object obj = ResourceManager.GetObject("help_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  IGNORED.
        /// </summary>
        internal static string Hook_Ignored {
            get {
                return ResourceManager.GetString("Hook_Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARAMETERS CHANGED to .
        /// </summary>
        internal static string Hook_Parameters_Changed {
            get {
                return ResourceManager.GetString("Hook_Parameters_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULT .
        /// </summary>
        internal static string Hook_Result {
            get {
                return ResourceManager.GetString("Hook_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap horizontal_16x16 {
            get {
                object obj = ResourceManager.GetObject("horizontal_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap horizontal2_16x16 {
            get {
                object obj = ResourceManager.GetObject("horizontal2_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap import_16 {
            get {
                object obj = ResourceManager.GetObject("import_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_16 {
            get {
                object obj = ResourceManager.GetObject("info_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap navigate_16x16 {
            get {
                object obj = ResourceManager.GetObject("navigate_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No Text&gt;.
        /// </summary>
        internal static string No_Text {
            get {
                return ResourceManager.GetString("No_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open_in_browser_16x16 {
            get {
                object obj = ResourceManager.GetObject("open_in_browser_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pictures_16 {
            get {
                object obj = ResourceManager.GetObject("pictures_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_options {
            get {
                object obj = ResourceManager.GetObject("play_options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Viewer.
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PropertyGrid {
            get {
                object obj = ResourceManager.GetObject("PropertyGrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready ....
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_16 {
            get {
                object obj = ResourceManager.GetObject("refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_16 {
            get {
                object obj = ResourceManager.GetObject("save_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string Set_Cat_AllowDragTooltipSelectable {
            get {
                return ResourceManager.GetString("Set_Cat_AllowDragTooltipSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Set_Cat_AutoHighlight {
            get {
                return ResourceManager.GetString("Set_Cat_AutoHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string Set_Cat_AutoRefreshIfWindowNotFound {
            get {
                return ResourceManager.GetString("Set_Cat_AutoRefreshIfWindowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Set_Cat_DisableTooltipOpacityOnMouseOver {
            get {
                return ResourceManager.GetString("Set_Cat_DisableTooltipOpacityOnMouseOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string Set_Cat_EnableFindWindowActivation {
            get {
                return ResourceManager.GetString("Set_Cat_EnableFindWindowActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        internal static string Set_Cat_HandleMessageResults {
            get {
                return ResourceManager.GetString("Set_Cat_HandleMessageResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Set_Cat_HideIntersection {
            get {
                return ResourceManager.GetString("Set_Cat_HideIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Set_Cat_HighlightingSteps {
            get {
                return ResourceManager.GetString("Set_Cat_HighlightingSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string Set_Cat_IgnoreUnVisibleWindows {
            get {
                return ResourceManager.GetString("Set_Cat_IgnoreUnVisibleWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Set_Cat_ProgramLanguage {
            get {
                return ResourceManager.GetString("Set_Cat_ProgramLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        internal static string Set_Cat_ResetBreakpointsOnChange {
            get {
                return ResourceManager.GetString("Set_Cat_ResetBreakpointsOnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        internal static string Set_Cat_ShowChangedParameterValues {
            get {
                return ResourceManager.GetString("Set_Cat_ShowChangedParameterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string Set_Cat_ShowDescriptions {
            get {
                return ResourceManager.GetString("Set_Cat_ShowDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string Set_Cat_ShowVerbs {
            get {
                return ResourceManager.GetString("Set_Cat_ShowVerbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string Set_Cat_ShowWindowTooltipDuringDrag {
            get {
                return ResourceManager.GetString("Set_Cat_ShowWindowTooltipDuringDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Set_Cat_TooltipOpacity {
            get {
                return ResourceManager.GetString("Set_Cat_TooltipOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Set_Cat_TopMost {
            get {
                return ResourceManager.GetString("Set_Cat_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Set_Cat_VerbsHeight {
            get {
                return ResourceManager.GetString("Set_Cat_VerbsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, &apos;Find Window&apos; can also select any control on the &apos;Find Window Tooltip&apos;.
        /// </summary>
        internal static string Set_Desc_AllowDragTooltipSelectable {
            get {
                return ResourceManager.GetString("Set_Desc_AllowDragTooltipSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, region of the selected window will be highlighted automatically.
        /// </summary>
        internal static string Set_Desc_AutoHighlight {
            get {
                return ResourceManager.GetString("Set_Desc_AutoHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, Windows List will be automatically refreshed to find the window which is selected by &apos;Find Window&apos; and not in the list at the moment.
        /// </summary>
        internal static string Set_Desc_AutoRefreshIfWindowNotFound {
            get {
                return ResourceManager.GetString("Set_Desc_AutoRefreshIfWindowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, &apos;Find Window Tooltip&apos; opacity will be 1 whenever mouse over on it.
        /// </summary>
        internal static string Set_Desc_DisableTooltipOpacityOnMouseOver {
            get {
                return ResourceManager.GetString("Set_Desc_DisableTooltipOpacityOnMouseOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, Window which Find Window currently over will be also selected in the Windows List.
        /// </summary>
        internal static string Set_Desc_EnableFindWindowActivation {
            get {
                return ResourceManager.GetString("Set_Desc_EnableFindWindowActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, Message results which Spying window will return, will be shown in the Message Log..
        /// </summary>
        internal static string Set_Desc_HandleMessageResults {
            get {
                return ResourceManager.GetString("Set_Desc_HandleMessageResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, during the highlighting intersected area between PV main window and highlighting are will not be highlighted.
        /// </summary>
        internal static string Set_Desc_HideIntersection {
            get {
                return ResourceManager.GetString("Set_Desc_HideIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the number of highlighting steps during Highlighting of a window region.
        /// </summary>
        internal static string Set_Desc_HighlightingSteps {
            get {
                return ResourceManager.GetString("Set_Desc_HighlightingSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, Unvisible windows will not be listed in the Windows List.
        /// </summary>
        internal static string Set_Desc_IgnoreUnVisibleWindows {
            get {
                return ResourceManager.GetString("Set_Desc_IgnoreUnVisibleWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language of the program.
        /// </summary>
        internal static string Set_Desc_ProgramLanguage {
            get {
                return ResourceManager.GetString("Set_Desc_ProgramLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, Removes all breakpoints when selected Window is changed.
        /// </summary>
        internal static string Set_Desc_ResetBreakpointsOnChange {
            get {
                return ResourceManager.GetString("Set_Desc_ResetBreakpointsOnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, changed window messages (either manuel or automatic) will be shown in the Message Log.
        /// </summary>
        internal static string Set_Desc_ShowChangedParameterValues {
            get {
                return ResourceManager.GetString("Set_Desc_ShowChangedParameterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, Descriptions will be visible in the Properties Grid.
        /// </summary>
        internal static string Set_Desc_ShowDescriptions {
            get {
                return ResourceManager.GetString("Set_Desc_ShowDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, Designer Verbs for the selected Window will be visible in the Properties Grid.
        /// </summary>
        internal static string Set_Desc_ShowVerbs {
            get {
                return ResourceManager.GetString("Set_Desc_ShowVerbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, during the &apos;Find Window&apos;, a Tooltip window which contains some information about the window which mouse current on it will be shown .
        /// </summary>
        internal static string Set_Desc_ShowWindowTooltipDuringDrag {
            get {
                return ResourceManager.GetString("Set_Desc_ShowWindowTooltipDuringDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the opacity of the &apos;Find Window Tooltip&apos;.
        /// </summary>
        internal static string Set_Desc_TooltipOpacity {
            get {
                return ResourceManager.GetString("Set_Desc_TooltipOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True, PV will always be Top of the other windows.
        /// </summary>
        internal static string Set_Desc_TopMost {
            get {
                return ResourceManager.GetString("Set_Desc_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the height of the Verbs section in the Property Grid..
        /// </summary>
        internal static string Set_Desc_VerbsHeight {
            get {
                return ResourceManager.GetString("Set_Desc_VerbsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Find Window Tooltip Selectable.
        /// </summary>
        internal static string Set_DispName_AllowDragTooltipSelectable {
            get {
                return ResourceManager.GetString("Set_DispName_AllowDragTooltipSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Highlight.
        /// </summary>
        internal static string Set_DispName_AutoHighlight {
            get {
                return ResourceManager.GetString("Set_DispName_AutoHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Refresh List If Window Not Found.
        /// </summary>
        internal static string Set_DispName_AutoRefreshIfWindowNotFound {
            get {
                return ResourceManager.GetString("Set_DispName_AutoRefreshIfWindowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Tooltip Opacity On Mouse Over.
        /// </summary>
        internal static string Set_DispName_DisableTooltipOpacityOnMouseOver {
            get {
                return ResourceManager.GetString("Set_DispName_DisableTooltipOpacityOnMouseOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Window During Find Window.
        /// </summary>
        internal static string Set_DispName_EnableFindWindowActivation {
            get {
                return ResourceManager.GetString("Set_DispName_EnableFindWindowActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle Message Results.
        /// </summary>
        internal static string Set_DispName_HandleMessageResults {
            get {
                return ResourceManager.GetString("Set_DispName_HandleMessageResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Intersected Area.
        /// </summary>
        internal static string Set_DispName_HideIntersection {
            get {
                return ResourceManager.GetString("Set_DispName_HideIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighting Count.
        /// </summary>
        internal static string Set_DispName_HighlightingSteps {
            get {
                return ResourceManager.GetString("Set_DispName_HighlightingSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Unvisible Windows.
        /// </summary>
        internal static string Set_DispName_IgnoreUnVisibleWindows {
            get {
                return ResourceManager.GetString("Set_DispName_IgnoreUnVisibleWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program UI Language.
        /// </summary>
        internal static string Set_DispName_ProgramLanguage {
            get {
                return ResourceManager.GetString("Set_DispName_ProgramLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Window Change Clear Breakpoints.
        /// </summary>
        internal static string Set_DispName_ResetBreakpointsOnChange {
            get {
                return ResourceManager.GetString("Set_DispName_ResetBreakpointsOnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Changed Messages.
        /// </summary>
        internal static string Set_DispName_ShowChangedParameterValues {
            get {
                return ResourceManager.GetString("Set_DispName_ShowChangedParameterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Descriptions.
        /// </summary>
        internal static string Set_DispName_ShowDescriptions {
            get {
                return ResourceManager.GetString("Set_DispName_ShowDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Verbs.
        /// </summary>
        internal static string Set_DispName_ShowVerbs {
            get {
                return ResourceManager.GetString("Set_DispName_ShowVerbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Window&apos;s Tooltip During Find Window.
        /// </summary>
        internal static string Set_DispName_ShowWindowTooltipDuringDrag {
            get {
                return ResourceManager.GetString("Set_DispName_ShowWindowTooltipDuringDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Window Tooltip Opacity.
        /// </summary>
        internal static string Set_DispName_TooltipOpacity {
            get {
                return ResourceManager.GetString("Set_DispName_TooltipOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Most.
        /// </summary>
        internal static string Set_DispName_TopMost {
            get {
                return ResourceManager.GetString("Set_DispName_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbs Height.
        /// </summary>
        internal static string Set_DispName_VerbsHeight {
            get {
                return ResourceManager.GetString("Set_DispName_VerbsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap software_16x16 {
            get {
                object obj = ResourceManager.GetObject("software_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop_16 {
            get {
                object obj = ResourceManager.GetObject("stop_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tab_16x16 {
            get {
                object obj = ResourceManager.GetObject("tab_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap web_16 {
            get {
                object obj = ResourceManager.GetObject("web_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window {
            get {
                object obj = ResourceManager.GetObject("window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Window_Normal {
            get {
                return ResourceManager.GetString("Window_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups!!!
        ///I couldn&apos;t find the window in the TreeView.
        ///Window you try to view might be created after the TreeView filled.
        ///Refreshing Windows list might fix this problem.
        ///Do you want to refresh Windows List?.
        /// </summary>
        internal static string Window_Not_Found_Msg {
            get {
                return ResourceManager.GetString("Window_Not_Found_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Not Found.
        /// </summary>
        internal static string Window_Not_Found_Title {
            get {
                return ResourceManager.GetString("Window_Not_Found_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Most.
        /// </summary>
        internal static string Window_TopMost {
            get {
                return ResourceManager.GetString("Window_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows {
            get {
                object obj = ResourceManager.GetObject("windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom_in_16 {
            get {
                object obj = ResourceManager.GetObject("zoom_in_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
